entryPoints:
  web-secure:
    address: :443

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedByDefault: false

certificatesResolvers:
  cf:
    acme:
      email: riley@rileymathews.com
      storage: /etc/traefik/cfacme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - 1.1.1.1:53
          - 8.8.8.8:53
